spring.application.name=TD5-Spring
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ingredient
spring.datasource.username=postgres
spring.datasource.password=fenitra

spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init.sql

spring.jpa.show-sql=false
logging.level.org.springframework.jdbc=DEBUG